language: rust
rust:
- nightly
os:
- linux
cache:
  cargo: true
  directories:
  - "$HOME/deps"
branches:
  only:
  - testing
  - master
script:
- bash scripts/travis-script.sh
after_success: |-
  [ $TRAVIS_BRANCH = master ] &&
  [ $TRAVIS_PULL_REQUEST = false ] &&
  sudo pip install ghp-import &&
  bash scripts/upload-doc.sh
env:
  global:
  - secure: RYMV1cbq4h0JsPvTV/fxiufQeTDvta/rFfg7nd6B/GCrYj9dVcWEFcFtaPbH8rKtpS/1sS5CxXm3GmJhoa/l0Wf6aKCvXD8C4VR5McKQR57o3ecp3/Se+iFEdI7K8AiE+uLMHFxPmGcdtiiSexOiQSdS1lt7K3Ow2HI4Ky+GheKreuxub8rCvlePrRjH8S0R4/cXM/NvwVt2dwXwsKbh+XPxJovPhjRmWxMQTftE7JGN3akpMwodEvShJm4+IlnYXGJ23Bun1rZRPYy91Ml2p13zeZMQZ/MNBSMUSdq4L65zzUX7mH+NQlkcJKFCWFOfnsWDGmo0eKtDYv+MLZF4DFI9YOkZ0YQFSfUthZjW321Y+w1uihtzY22YPjsVP2a1vu+Ydk9jkRKRRR/s6jxAo9SEGwxhGi12K+0ZS8Scf/RtKqOlmDBL2gCfu+lSU+KiVWY7mrBEcR8FnKzEeGxJBjFovOOH6Oluui/9AGbhtF3d1vSWLk6vx5H8+g6dNcRi+eCJmtHWHx14bLebmeMbAZpYVojO+/NQYaJAfF0koMSDjtzN/4V1EAKZMG4E8zcdqEV5Arq1mUP3agCgOdU/+UE1k+tLvghUqD4IWtwpjW32a1g7kBKY4nzp6jW7AGp0WBT2AAamP99p0l1H5nAhS9H0VrAfzNfOWsLd4TFNHaU=
